# gender_od_train_OpenImageData.yaml

task: detect
mode: train

data: config/gender_od_train_OpenImageData_setting.yaml
project: Gender_od
name: yolov8n-oiv7_openimages_finetune
epochs: 300
batch: 256
imgsz: 640
device: 0,1
save: True
save_period: 100
cache: False
workers: 4
exist_ok: False
pretrained: True
verbose: True
seed: 0
single_cls: False
resume: False
amp: True
freeze: null

# Optimizer
optimizer: AdamW
lr0: 0.001
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8

# Augmentation
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.1
shear: 0.0
perspective: 0.0
fliplr: 0.5
flipud: 0.0
mosaic: 1.0
mixup: 0.0
